# Generated by Django 4.2.7 on 2025-07-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_filial_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='region',
        ),
        migrations.AddField(
            model_name='filial',
            name='universitet',
            field=models.CharField(choices=[('narxoz', 'Narxoz'), ('fiskal', 'Fiskal'), ('moliya', 'Moliya')], default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
