# Generated by Django 4.2.7 on 2025-07-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_positionapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='positions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('director', 'Direktor'), ('manager', 'Menejer'), ('developer', 'Dasturchi'), ('designer', 'Dizayner'), ('accountant', 'Buxgalter'), ('hr', "Kadrlar bo'limi xodimi"), ('marketer', 'Marketolog'), ('operator', 'Operator'), ('engineer', 'Muhandis'), ('technician', 'Texnik xodim')], default='developer', max_length=50),
        ),
    ]
