# Generated by Django 4.2.7 on 2025-07-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_employee_positions_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='distance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
