# Generated by Django 4.2.7 on 2025-07-23 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_unknownface_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCameraStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('face_image', models.ImageField(upload_to='face_results/stats/%Y/%m/%d/')),
                ('distance', models.CharField(blank=True, max_length=10, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.camera')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'camera', 'timestamp'], name='attendance__employe_8443f9_idx')],
            },
        ),
    ]
