# Generated by Django 4.2.7 on 2025-07-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_employeecamerastats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('narxoz', 'Narxoz'), ('fiskal', 'Fiskal'), ('moliya', 'Moliya')], max_length=50),
        ),
    ]
