# Generated by Django 4.2.7 on 2025-07-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_employee_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='universitet',
            field=models.CharField(choices=[('narxoz', 'Narxoz'), ('fiskal', 'Fiskal'), ('moliya', 'Moliya')], max_length=50),
        ),
    ]
